### ISSUE TITLE
Use KivyMD instead of Kivy

### ISSUE THREAD

**Issue by p0lygun** [Gorgeous-Ghouls/Blak#12]
We can use kivyMD instead of Kivy as that makes theming very easy
[KivyMD](https://github.com/kivymd/KivyMD)
[kivyMD docs](https://kivymd.readthedocs.io/en/latest/)

**Comment by p0lygun** [comment]
@noahlias your thoughts on this ?

**Comment by noahlias** [comment]
it looks like mobile phone app, create some compoments more easier. i agree

**Comment by StoneSteel27** [comment]
Yes i agree too

**Comment by StoneSteel27** [comment]
well this is a code jam, so we should asap finish it, we need time for adding theme features
