### ISSUE TITLE
Add colums where chats are show

### ISSUE THREAD

**Issue by p0lygun** [Gorgeous-Ghouls/Blak#16]
Make use of Screen in KivyMD, Each chat is a separate screen

The column on the left lists all the chats available 
Each entry acts as button to switch to a new screen in "chat area"
Image for reference 

![Image](https://user-images.githubusercontent.com/22869882/180664719-bfed47f6-f00a-471a-92ba-7d9924123b69.png)

"the Chats" are actually just a screen and we them switch them via the listings on the left

**Comment by noahlias** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
