### ISSUE TITLE
need to press enter twice or use shift + enter

### ISSUE THREAD

**Issue by p0lygun** [Gorgeous-Ghouls/Blak#49]

**Comment by p0lygun** [comment]
@noahlias try to add this 
checkout main, create a new branch like `feature/custom-send`

**Comment by p0lygun** [comment]
@noahlias 
add the logic to https://github.com/Gorgeous-Ghouls/Blak/blob/f806fb695fdffe34a45c9ca78f0d6d2b822ee662/client/app/ui/__init__.py#L143-L154

check for `self.times_validated` and execute logic accordingly

**Comment by noahlias** [comment]
ok, I understand
